#################################################################################
# Pipeline to clean up registry from artifacts and docker images
#################################################################################
name: Cleanup Registry
env:
  RUST_BACKTRACE: "1"
  CARGO_TERM_COLOR: always
permissions:
  contents: read
on:
  schedule:
    - cron: "30 1 * * *" # Daily at 01:30 UTC

jobs:
  cleanup-registry:
    name: Cleanup Registry
    runs-on: self-hosted-hoprnet-small
    timeout-minutes: 30
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          disable-sudo: false
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Setup GCP
        uses: hoprnet/hopr-workflows/actions/setup-gcp@setup-gcp-v1
        with:
          google_credentials: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
          install_sdk: "true"
      - name: Setup Nix
        uses: hoprnet/hopr-workflows/actions/setup-nix@setup-nix-v1
        with:
          cachix_cache_name: hopr-workflows
          cachix_auth_token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Cleanup Docker images
        timeout-minutes: 20
        run: nix run .#cleanup-docker-images -- "${{ vars.DOCKER_IMAGE_REGISTRY }}"
      - name: Cleanup Artifact files
        timeout-minutes: 20
        run: nix run .#cleanup-artifact-files -- -p hoprassociation -l europe-west3 -r rust-binaries